//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    
    public partial class EventDetail
    {
        [DisplayName("Event Details ID")]
        public long EventDetailID { get; set; }
        [DisplayName("Event Status ID")]
        public short FK_EventDetailStatusID { get; set; }
        [DisplayName("Event  ID")]
        public long FK_EventID { get; set; }
        [DisplayName("Event Details Name")]
        public string EventDetailName { get; set; }
        [DisplayName("Event Details Number")]
        public Nullable<short> EventDetailNumber { get; set; }
        [DisplayName("Event Details Odd")]
        public Nullable<decimal> EventDetailOdd { get; set; }
        [DisplayName("Finishing Position")]
        public Nullable<short> FinishingPosition { get; set; }
        [DisplayName("First Timer")]
        public Nullable<bool> FirstTimer { get; set; }
        [DisplayName("Event  ID")]
        public virtual Event Event { get; set; }
        [DisplayName("Event Status ID")]
        public virtual EventDetailStatu EventDetailStatu { get; set; }
    }
}
