//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.EventDetails = new HashSet<EventDetail>();
        }
        [DisplayName("Event ID")]
        public long EventID { get; set; }
        [DisplayName("Tournament ID")]
        public long FK_TournamentID { get; set; }
        [DisplayName("Event Name")]
        public string EventName { get; set; }
        [DisplayName("Event  Number")]
        public Nullable<short> EventNumber { get; set; }
        [DisplayName("Event Start Date")]
        public Nullable<System.DateTime> EventDateTime { get; set; }
        [DisplayName("Event End Date")]
        public Nullable<System.DateTime> EventEndDateTime { get; set; }
        [DisplayName("Auto Close")]
        public Nullable<bool> AutoClose { get; set; }
    
        public virtual Tournament Tournament { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventDetail> EventDetails { get; set; }
    }
}
